#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    powerExpanderBattery, sensorAnalog)
#pragma config(Sensor, dgtl12, pincer,         sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           arm_l1,        tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           arm_l2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           arm_l3,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           chassis_l1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           chassis_l2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           chassis_r2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           chassis_r1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           arm_r3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           arm_r2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          arm_r1,        tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Mod_Vex_Comp_Control.c"
#include "motor.h"

int iDes;
void
armControl (bool bSpeedBoost, bool bBtnUp, bool bBtnDown) {
	int iOutput;
	if (bBtnUp || bBtnDown) {
		iOutput = bSpeedBoost ? (bBtnUp - bBtnDown) * 127 : (bBtnUp - bBtnDown) * 60;
		iDes = (SensorValue[I2C_1] + SensorValue[I2C_2]) / 2;
	} else {
		iOutput = iArmPID(iDes);
	}
	arm (iOutput);
}

void
initIO () {
	bPlaySounds = true;	

	while (SensorValue[powerExpanderBattery] < 250) {
		displayLCDCenteredString(0, "PLUG IN POWER");
		displayLCDCenteredString(1, "EXPANDER!");
		playSound(soundException);
	}
	clearSounds();

	sTeam = "Hornet ~ 21S";
	bLCDAuton =
	bLCDUserControl =  true;
}

void
pre_auton () {
	clearAllIME();
}

task
autonomous () {
}

task 
usercontrol () {
	while (true) {
		tank       ( (vexRT[Ch3]), (vexRT[Ch2]) );
		armControl ( vexRT[Btn6D], vexRT[Btn6U], vexRT[Btn5U] );
		
		SensorValue[pincer] = vexRT[Btn5D];
	}
}
